name=input("enter your name:")
age=int(input("enter your age:"))
city=input("enter your city:")
college_name=input("enter your college name:")
print("name:",name)
print(f"age:{age}")
print("city:",city)
print("college name:",college_name)